version: "3.3"

services:
    # mongodb:
    #     image: mongo
    #     container_name: logmongo
    #     ports: 
    #         - 27017:27017
    fluentd-custom:
        image: custom-fluend-plugin:1.0.0
        build:
            context: ./build
            dockerfile: dockerfile
        container_name: fluentd-custom
        volumes:
            - "./config/config.conf:/fluentd/etc/config.conf"
        ports:
            - 24224:24224
        logging: 
            driver: "syslog"

        
        

